version: 2.0.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  version: '{version}'
  file_version: '{version}'
  package_version: '{version}'
  informational_version: $(APPVEYOR_REPO_BRANCH):$(APPVEYOR_REPO_COMMIT)
before_build:
  - cmd: |
      setlocal enabledelayedexpansion
      setlocal EnableExtensions

      REM Set version attributes..
      Tools\UnixUtils\sed.exe -i -e "s|0\.0\.0\.0|%APPVEYOR_BUILD_VERSION%|g" Mono.CairoWarp\Mono.CairoWarp.csproj
      Tools\UnixUtils\sed.exe -i -e "s|GIT_COMMIT|%APPVEYOR_REPO_COMMIT%|g" Mono.CairoWarp\Mono.CairoWarp.csproj
      Tools\UnixUtils\sed.exe -i -e "s|VERSION_STRING|%APPVEYOR_REPO_BRANCH%:%APPVEYOR_REPO_COMMIT%|g" Mono.CairoWarp\Mono.CairoWarp.csproj

      REM Restoring NuGet packages..
      appveyor-retry nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: NoKeyNoParty
    on:
      branch: master
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
